version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Specify the dependencies
python:
  install:
    - requirements: docs/requirements.txt
